# Config for the vehicle

# Each module is a seperate system that needs to be started up
Modules:
    # Object that creates the vehicle interface
    Vehicle:
        # The full name of the class to instantiate in this case its a wrapper
        # for the base C++ vehicle
        type: vehicle.vehicle.Vehicle
        # Time between updates in ms
        update_interval: 100

        # The list of devices to create for the vehicle
        Devices:
            # NOTE: All current numbers here are BS and need to updated

            # This entry creates a thruster
            StarboardThruster:
                # Notice this is from the 'ext' package, this package contains
                # all the wrapped C++ classes
                type: ext.vehicle_device.Thruster
                # String representing the address of the thruster
                address: "01"
                # Number determined by testing
                calibration_factor: 0.45
                # Number used to flip thruster forces (if thruster is reversed
                # on the vehicle)
                direction: 1

            PortThruster:
                type: ext.vehicle_device.Thruster
                address: "02"
                calibration_factor: 0.45
                direction: 1

            ForeThruster:
                type: ext.vehicle_device.Thruster
                address: "03"
                calibration_factor: 0.45
                direction: 1

            AftThruster:
                type: ext.vehicle_device.Thruster
                address: "04"
                calibration_factor: 0.45
                direction: 1

        
        
    
    
    